version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mounts the current directory into the container
    env_file:
      - .env
    depends_on:
      - db  # Ensures the web service waits for the db to be ready

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persists database data across restarts
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local  # Tells Docker to use a local volume to store data
